# This is a basic workflow to help you get started with Actions

name: My CI-CT job name

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Create Directory
        run: |
          mkdir DirectoryForMyReports

      # Install NodeJS
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Install Newman & HTMLExtra
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run Postman collection
      - name : Run the postman collection
        run : |
          newman run "reqResRESTAPI.postman_collection.json" -e "QA.postman_environment.json" -r htmlextra --reporter-htmlextra-export DirectoryForMyReports/SanityRun.html

      # Publish the generated report
      - name : Publish Sanity Report
        uses : actions/upload-artifact@v4
        with :
          name : Reports
          path : DirectoryForMyReports
      
