name: First-Test
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Creates directory
        run: |
          mkdir Result


      # Install Node on the runner
      - name: Install Node
        # uses: actions/setup-node@v1
        uses: actions/checkout@v3
        with:
          node-version: "17.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      # - name: Make Directory for results
        # run: mkdir -p apiFunctionalTestResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run https://api.postman.com/collections/16542258-af95fb48-d8ba-45a9-bd02-26de5ff9e4c7?access_key=PMAT-01HWTE03PCJH0S68J30GWNWR0C -r htmlextra --reporter-htmlextra-export Result/htmlreport.html


      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: Result
